?start: statement*

statement: compound_statement
         | selection_statement
         | iteration_statement
         | jump_statement
         | preach_statement
         | declaration 
         | tuple_declaration
         | list_declaration
         | array_declaration 
         | function_definition

tuple_declaration: "TypeKeyword(value='tuple')" "IDENTIFIER" "Operator(value='=')" "Symbols(value='(')" assignment_expression value_list "Symbols(value=')')" "ENDOFSTMT" 

list_declaration: "TypeKeyword(value='list')" "IDENTIFIER" "Operator(value='=')" "Symbols(value='[')" value_list "Symbols(value=']')" "ENDOFSTMT" 

value_list: ("Symbols(value=',')" assignment_expression)* 

compound_statement: "Symbols(value='{')" declaration* statement* "Symbols(value='}')"

declaration: declaration_specifier? assignment_expression "ENDOFSTMT"
        | array_declaration "ENDOFSTMT"

declaration_specifier: "Keyword(value='eternal')"? type_specifier

type_specifier: "TypeKeyword(value='void')"
              | "TypeKeyword(value='char')"
              | "TypeKeyword(value='int')"
              | "TypeKeyword(value='float')"
              | "TypeKeyword(value='bool')"

preach_statement: "Keyword(value='preach')" "Symbols(value='(')" expression "Symbols(value=')')" "ENDOFSTMT"

selection_statement: "Keyword(value='belief')" "Symbols(value='(')" expression "Symbols(value=')')" statement
                   | "Keyword(value='belief')" "Symbols(value='(')" expression "Symbols(value=')')" statement "Keyword(value='else')" statement

iteration_statement: "Keyword(value='pledge')" "Symbols(value='(')" expression "Symbols(value=')')" statement
                   | "Keyword(value='oath')" statement "Keyword(value='pledge')" "Symbols(value='(')" expression "Symbols(value=')')" "ENDOFSTMT"
                   | "Keyword(value='chant')" "Symbols(value='(')" declaration_specifier? assignment_expression "ENDOFSTMT" expression? "ENDOFSTMT" expression? "Symbols(value=')')" statement 

jump_statement: "Keyword(value='persist')" "ENDOFSTMT"
              | "Keyword(value='retreat')" "ENDOFSTMT"
              | "Keyword(value='deliver')" expression? "ENDOFSTMT"

assignment_expression:  expression
                      | postfix_expression assignment_operator assignment_expression

assignment_operator: "Operator(value='=')"
                   | "Operator(value='*=')"
                   | "Operator(value='/=')"
                   | "Operator(value='%=')"
                   | "Operator(value='+=')"
                   | "Operator(value='-=')"

expression: logical_or_expression

logical_or_expression: logical_and_expression
                     | logical_or_expression "Operator(value='||')" logical_and_expression

logical_and_expression: and_expression
                      | logical_and_expression "Operator(value='&&')" and_expression

and_expression: equality_expression
              | and_expression "Operator(value='&')" equality_expression

equality_expression: relational_expression
                    | equality_expression "Operator(value='==')" relational_expression
                    | equality_expression "Operator(value='!=')" relational_expression

relational_expression: additive_expression
                     | relational_expression "Operator(value='<')" additive_expression
                     | relational_expression "Operator(value='>')" additive_expression
                     | relational_expression "Operator(value='<=')" additive_expression
                     | relational_expression "Operator(value='>=')" additive_expression

additive_expression: multiplicative_expression
                   | additive_expression "Operator(value='+')" multiplicative_expression
                   | additive_expression "Operator(value='-')" multiplicative_expression

multiplicative_expression: postfix_expression
                         | multiplicative_expression "Operator(value='*')" postfix_expression
                         | multiplicative_expression "Operator(value='/')" postfix_expression
                         | multiplicative_expression "Operator(value='%')" postfix_expression

postfix_expression: function_call 
                  | postfix_expression "Operator(value='++')"
                  | postfix_expression "Operator(value='--')"
                  | primary_expression

primary_expression: "IDENTIFIER"
                  | "INTEGER"
                  | "FLOAT"
                  | "STRING"
                  | "BOOLEAN"
                  | "Symbols(value='(')" expression "Symbols(value=')')"
                  | "IDENTIFIER" "Symbols(value='.')" list_op 
                  | "IDENTIFIER" "Symbols(value='.')" tuple_op
                  | "IDENTIFIER" "Symbols(value='.')'" array_op
                  | "IDENTIFIER" "Symbols(value='[')" "IDENTIFIER" "Symbols(value=']')"  

list_op: "UtilityFunction(value='head')" "ENDOFSTMT"
        | "UtilityFunction(value='tail')" "ENDOFSTMT"
        | "UtilityFunction(value='length')"
        | "UtilityFunction(value='cons')" "Symbols(value='(')" expression "Symbols(value=')')" "ENDOFSTMT"
        | "UtilityFunction(value='append')" "Symbols(value='(')" expression "Symbols(value=')')" "ENDOFSTMT"
        | "UtilityFunction(value='insert')" "Symbols(value='(')" expression "Symbols(value=',')" expression "Symbols(value=')')" "ENDOFSTMT"

tuple_op: "UtilityFunction(value='head')" "ENDOFSTMT"
        | "UtilityFunction(value='tail')" "ENDOFSTMT"
        | "UtilityFunction(value='cons')" "Symbols(value='(')" expression "Symbols(value=')')"
        | "UtilityFunction(value='length')"

array_op: "UtilityFunction(value='length')"
        | "UtilityFunction(value='append')" "Symbols(value='(')" expression "Symbols(value=')')" "ENDOFSTMT"
        | "UtilityFunction(value='remove')" "Symbols(value='(')" expression "Symbols(value=')')" "ENDOFSTMT"
        | "Symbols(value='[')" expression "Symbols(value=']')"

function_definition: "Keyword(value='invoke')" type_specifier "IDENTIFIER" "Symbols(value='(')" parameter_list "Symbols(value=')')" function_body

parameter_list: (type_specifier "IDENTIFIER" ("Symbols(value=',')" type_specifier "IDENTIFIER")*)?

function_body: "Symbols(value='{')" (declaration | statement)* "Symbols(value='}')"

function_call: "IDENTIFIER" "Symbols(value='(')" assignment_expression value_list "Symbols(value=')')" 

array_declaration: "TypeKeyword(value='array')" "Operator(value='<')" type_specifier "Operator(value='>')" "IDENTIFIER" "Operator(value='=')" "Symbols(value='[')" expression ("Symbols(value=',') " expression)* "Symbols(value=']')" "ENDOFSTMT"


%import common.LETTER
%import common.DIGIT
%import common.CNAME
%import common.INT 
%import common.FLOAT
%import common.ESCAPED_STRING
%import common.WS
%ignore WS
